name: build
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test (race)
        run: go test -mod vendor ./... -race