name: Go
on: [push]
jobs:
  build:
    name: Build with Go 1.13
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Test
        run: go test -mod vendor ./...
      - name: Build
        run: go build -mod vendor
